./gameboy BROKER CAUGHT_POKEMON 1 OK
./gameboy BROKER CAUGHT_POKEMON 2 FAIL
./gameboy BROKER NEW_POKEMON Pikachu 2 3 1
./gameboy BROKER CATCH_POKEMON Onyx 4 5
./gameboy BROKER CATCH_POKEMON Charmander 4 5
./gameboy BROKER CATCH_POKEMON Pikachu 9 3 
./gameboy BROKER CATCH_POKEMON Squirtle 9 3 
./gameboy BROKER CAUGHT_POKEMON 10 OK
./gameboy BROKER CAUGHT_POKEMON 11 FAIL
./gameboy BROKER CATCH_POKEMON Bulbasaur 1 7
./gameboy BROKER CATCH_POKEMON Charmander 1 7 
./gameboy BROKER GET_POKEMON Pichu
./gameboy BROKER GET_POKEMON Raichu
./gameboy BROKER GET_POKEMON Pikachu
./gameboy BROKER GET_POKEMON Charmander
./gameboy BROKER CAUGHT_POKEMON 1 OK
./gameboy BROKER CAUGHT_POKEMON 2 FAIL
./gameboy BROKER CATCH_POKEMON Pikachu 2 3
./gameboy BROKER CATCH_POKEMON Squirtle 5 2
./gameboy BROKER CATCH_POKEMON Onyx 4 5
./gameboy BROKER CATCH_POKEMON Vaporeon 4 5
./gameboy BROKER CAUGHT_POKEMON 1 OK
./gameboy BROKER CAUGHT_POKEMON 2 FAIL
./gameboy BROKER CATCH_POKEMON Pikachu 2 3
./gameboy BROKER CATCH_POKEMON Squirtle 5 2
./gameboy BROKER CATCH_POKEMON Onyx 4 5
./gameboy BROKER CATCH_POKEMON Charmander 4 5
./gameboy BROKER APPEARED_POKEMON Pikachu 9 9
./gameboy BROKER APPEARED_POKEMON Squirtle 5 2
./gameboy BROKER APPEARED_POKEMON Jolteon 2 2
./gameboy BROKER APPEARED_POKEMON Flareon 4 6
./gameboy BROKER APPEARED_POKEMON Onix 2 8
./gameboy BROKER APPEARED_POKEMON Gengar 6 6
./gameboy BROKER APPEARED_POKEMON Squirtle 5 5
./gameboy BROKER APPEARED_POKEMON Umbreon 10 6
./gameboy BROKER APPEARED_POKEMON Espeon 7 1
./gameboy BROKER APPEARED_POKEMON Vaporeon 4 10
./gameboy BROKER CATCH_POKEMON Onyx 7 10
./gameboy BROKER CATCH_POKEMON Charmander 2 6
./gameboy BROKER APPEARED_POKEMON Pikachu 9 6
./gameboy BROKER APPEARED_POKEMON Squirtle 6 9
./gameboy BROKER APPEARED_POKEMON Jolteon 5 4
./gameboy BROKER APPEARED_POKEMON Flareon 3 1
./gameboy BROKER APPEARED_POKEMON Onix 5 2
./gameboy BROKER APPEARED_POKEMON Gengar 5 8
./gameboy BROKER APPEARED_POKEMON Squirtle 6 5
./gameboy BROKER APPEARED_POKEMON Umbreon 9 7
./gameboy BROKER APPEARED_POKEMON Espeon 7 2
./gameboy BROKER APPEARED_POKEMON Vaporeon 6 10
./gameboy BROKER CAUGHT_POKEMON 8 OK
./gameboy BROKER CAUGHT_POKEMON 6 FAIL
./gameboy BROKER NEW_POKEMON Pikachu 3 5 1
./gameboy BROKER CATCH_POKEMON Onyx 4 5
./gameboy BROKER CATCH_POKEMON Charmander 4 5
./gameboy BROKER CATCH_POKEMON Pikachu 9 6 
./gameboy BROKER CATCH_POKEMON Squirtle 8 3 
./gameboy BROKER CAUGHT_POKEMON 10 FAIL
./gameboy BROKER CAUGHT_POKEMON 11 OK
./gameboy BROKER CATCH_POKEMON Bulbasaur 1 7
./gameboy BROKER CATCH_POKEMON Charmander 1 7 
./gameboy BROKER GET_POKEMON Pikachu
./gameboy BROKER GET_POKEMON Charmander
./gameboy BROKER CAUGHT_POKEMON 1 OK
./gameboy BROKER CAUGHT_POKEMON 2 FAIL
./gameboy BROKER CATCH_POKEMON Pikachu 2 3
./gameboy BROKER CATCH_POKEMON Squirtle 5 2
./gameboy BROKER CATCH_POKEMON Onyx 4 5
./gameboy BROKER CATCH_POKEMON Vaporeon 4 5
./gameboy BROKER CAUGHT_POKEMON 11 FAIL
./gameboy BROKER CATCH_POKEMON Bulbasaur 1 7
./gameboy BROKER CATCH_POKEMON Charmander 1 7 
./gameboy BROKER GET_POKEMON Pichu
./gameboy BROKER GET_POKEMON Raichu
./gameboy BROKER GET_POKEMON Pikachu
./gameboy BROKER GET_POKEMON Charmander
./gameboy BROKER CAUGHT_POKEMON 1 OK
./gameboy BROKER CAUGHT_POKEMON 2 FAIL
./gameboy BROKER CATCH_POKEMON Onyx 4 5
./gameboy BROKER CATCH_POKEMON Charmander 4 5
./gameboy BROKER APPEARED_POKEMON Pikachu 9 9
./gameboy BROKER APPEARED_POKEMON Squirtle 5 2
./gameboy BROKER APPEARED_POKEMON Jolteon 2 2
./gameboy BROKER APPEARED_POKEMON Flareon 4 6
./gameboy BROKER APPEARED_POKEMON Onix 2 8
./gameboy BROKER APPEARED_POKEMON Gengar 6 6
./gameboy BROKER APPEARED_POKEMON Squirtle 5 5
./gameboy BROKER APPEARED_POKEMON Umbreon 10 6
./gameboy BROKER APPEARED_POKEMON Espeon 7 1
./gameboy BROKER CATCH_POKEMON Onyx 4 5
./gameboy BROKER CATCH_POKEMON Charmander 4 5
./gameboy BROKER APPEARED_POKEMON Pikachu 9 9
./gameboy BROKER APPEARED_POKEMON Squirtle 5 2
./gameboy BROKER APPEARED_POKEMON Jolteon 2 2
./gameboy BROKER APPEARED_POKEMON Flareon 4 6
./gameboy BROKER APPEARED_POKEMON Onix 2 8
./gameboy BROKER APPEARED_POKEMON Gengar 6 6
./gameboy BROKER APPEARED_POKEMON Squirtle 5 5
./gameboy BROKER APPEARED_POKEMON Umbreon 10 6
./gameboy BROKER APPEARED_POKEMON Espeon 7 1